### ISSUE TITLE
Issue in agents communication via wallet guide 

### ISSUE THREAD

**Issue by FelixNicolaeBucsa** [fetchai/uAgents#483] opened 2024-08-06 10:47 UTC
### Prerequisites

- [X] I checked the [documentation](https://fetch.ai/docs) and found no answer to my problem
- [X] I checked the [existing issues](https://github.com/fetchai/uAgents/issues) and made sure there are no similar bug reports

### Category

Bug (unexpected behavior)

### Getting error:

<img width="1300" alt="Screenshot 2024-06-27 at 8 38 32 PM" src="https://github.com/fetchai/docs-v2/assets/111856910/93551f1a-6ae8-44b5-a015-9f8e1f1132de">

### Debugging:

As it showing babble module not found, as the error inside the uagent package library but still I try to install the babble by using “pip install babble”

But still getting error: \

<img width="1301" alt="Screenshot 2024-06-27 at 8 38 48 PM" src="https://github.com/fetchai/docs-v2/assets/111856910/82b5fc9b-96e7-4aa2-a1f3-19805151b568">

**ISSUE OPENED IN DOCS REPO**: https://github.com/fetchai/docs/issues/734

### Version

v0.14.0

**Comment by Archento** [comment] 2024-08-09 09:47
This should be fixed by installing the `fetch-babble` extension when installing uagents via poetry or directly installing the package through pip.

Install via uagents extras:
```bash
pip install 'uagents[fetchai-babble]'
```
or simply the package itself:
```bash
pip install fetchai-babble'
```

Installing `babble` will install the wrong package: [pypi babble](https://pypi.org/project/babble/) which apparently is a Python library for parsing PDFs.

**Comment by abhifetch** [comment] 2024-08-19 13:44
Hi @jrriehl/ @Archento ,

I have installed the correct package using `pip install fetchai-babble` in terminal.
I have been using example from repo: https://github.com/fetchai/uAgents/blob/main/python/examples/15-wallet-messaging/main.py

Still it throws the same error related to babble. 

```
abhimanyugangani@Abhimanyus-MacBook-Pro New Integrations % python3 wallet.py                     
Traceback (most recent call last):
  File "/Users/abhimanyugangani/Desktop/Fetch.AI/integrations/New Integrations/wallet.py", line 2, in <module>
    from uagents.wallet_messaging import WalletMessage
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/uagents/wallet_messaging.py", line 7, in <module>
    from babble import Client
ImportError: cannot import name 'Client' from 'babble' (unknown location)
abhimanyugangani@Abhimanyus-MacBook-Pro New Integrations % 
```

Note: I have unsintalled the babble from my machine and installed the one provided by you.

**Comment by Archento** [comment] 2024-08-20 09:48
I just checked out the most recent version and installed in a virtual environment and everything works as intended.

> Please make sure that the Python interpreter points to the correct packages and that no conflicting packages are installed. Also try using a freshly set up poetry environment which ensures that no modules interfere.

As this seems to be a local error I'll go ahead and close this issue again. Feel free to reach out if you have any uAgents related issues and check the docs for tips on setting up your system.

**Closed by Archento** 2024-08-20 09:48 UTC
